# Project: Catherine Framework (https://github.com/jinxsecurity/catherine)
# Author: azazelm3dj3d (https://github.com/azazelm3dj3d)
# License: BSD 2-Clause

hex.so:
	cc c_hex_dump.c -Wall -shared -o dist/hex.so