# Project: Catherine Framework (https://github.com/battleoverflow/catherine)
# Author: battleoverflow (https://github.com/battleoverflow)
# License: BSD 2-Clause

hex.so:
	cc c_hex_dump.c -Wall -shared -o dist/hex.so
