# Project: Catherine Framework (https://github.com/azazellabs/catherine)
# Author: Azazel Labs (https://github.com/azazellabs)
# License: BSD 2-Clause

hex.so:
	cc c_hex_dump.c -Wall -shared -o dist/hex.so